# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spartan322/Projects/CPP/EmpireMod/Empire

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spartan322/Projects/CPP/EmpireMod/Empire

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spartan322/Projects/CPP/EmpireMod/Empire/CMakeFiles /home/spartan322/Projects/CPP/EmpireMod/Empire/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spartan322/Projects/CPP/EmpireMod/Empire/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named empire

# Build rule for target.
empire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 empire
.PHONY : empire

# fast build rule for target.
empire/fast:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/build
.PHONY : empire/fast

Source/Application.o: Source/Application.cpp.o

.PHONY : Source/Application.o

# target to build an object file
Source/Application.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Application.cpp.o
.PHONY : Source/Application.cpp.o

Source/Application.i: Source/Application.cpp.i

.PHONY : Source/Application.i

# target to preprocess a source file
Source/Application.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Application.cpp.i
.PHONY : Source/Application.cpp.i

Source/Application.s: Source/Application.cpp.s

.PHONY : Source/Application.s

# target to generate assembly for a file
Source/Application.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Application.cpp.s
.PHONY : Source/Application.cpp.s

Source/ResourceManager/ResourceHolder.o: Source/ResourceManager/ResourceHolder.cpp.o

.PHONY : Source/ResourceManager/ResourceHolder.o

# target to build an object file
Source/ResourceManager/ResourceHolder.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/ResourceManager/ResourceHolder.cpp.o
.PHONY : Source/ResourceManager/ResourceHolder.cpp.o

Source/ResourceManager/ResourceHolder.i: Source/ResourceManager/ResourceHolder.cpp.i

.PHONY : Source/ResourceManager/ResourceHolder.i

# target to preprocess a source file
Source/ResourceManager/ResourceHolder.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/ResourceManager/ResourceHolder.cpp.i
.PHONY : Source/ResourceManager/ResourceHolder.cpp.i

Source/ResourceManager/ResourceHolder.s: Source/ResourceManager/ResourceHolder.cpp.s

.PHONY : Source/ResourceManager/ResourceHolder.s

# target to generate assembly for a file
Source/ResourceManager/ResourceHolder.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/ResourceManager/ResourceHolder.cpp.s
.PHONY : Source/ResourceManager/ResourceHolder.cpp.s

Source/Sim/Colony.o: Source/Sim/Colony.cpp.o

.PHONY : Source/Sim/Colony.o

# target to build an object file
Source/Sim/Colony.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/Colony.cpp.o
.PHONY : Source/Sim/Colony.cpp.o

Source/Sim/Colony.i: Source/Sim/Colony.cpp.i

.PHONY : Source/Sim/Colony.i

# target to preprocess a source file
Source/Sim/Colony.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/Colony.cpp.i
.PHONY : Source/Sim/Colony.cpp.i

Source/Sim/Colony.s: Source/Sim/Colony.cpp.s

.PHONY : Source/Sim/Colony.s

# target to generate assembly for a file
Source/Sim/Colony.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/Colony.cpp.s
.PHONY : Source/Sim/Colony.cpp.s

Source/Sim/Person.o: Source/Sim/Person.cpp.o

.PHONY : Source/Sim/Person.o

# target to build an object file
Source/Sim/Person.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/Person.cpp.o
.PHONY : Source/Sim/Person.cpp.o

Source/Sim/Person.i: Source/Sim/Person.cpp.i

.PHONY : Source/Sim/Person.i

# target to preprocess a source file
Source/Sim/Person.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/Person.cpp.i
.PHONY : Source/Sim/Person.cpp.i

Source/Sim/Person.s: Source/Sim/Person.cpp.s

.PHONY : Source/Sim/Person.s

# target to generate assembly for a file
Source/Sim/Person.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/Person.cpp.s
.PHONY : Source/Sim/Person.cpp.s

Source/Sim/World.o: Source/Sim/World.cpp.o

.PHONY : Source/Sim/World.o

# target to build an object file
Source/Sim/World.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/World.cpp.o
.PHONY : Source/Sim/World.cpp.o

Source/Sim/World.i: Source/Sim/World.cpp.i

.PHONY : Source/Sim/World.i

# target to preprocess a source file
Source/Sim/World.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/World.cpp.i
.PHONY : Source/Sim/World.cpp.i

Source/Sim/World.s: Source/Sim/World.cpp.s

.PHONY : Source/Sim/World.s

# target to generate assembly for a file
Source/Sim/World.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Sim/World.cpp.s
.PHONY : Source/Sim/World.cpp.s

Source/Util/Common.o: Source/Util/Common.cpp.o

.PHONY : Source/Util/Common.o

# target to build an object file
Source/Util/Common.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Util/Common.cpp.o
.PHONY : Source/Util/Common.cpp.o

Source/Util/Common.i: Source/Util/Common.cpp.i

.PHONY : Source/Util/Common.i

# target to preprocess a source file
Source/Util/Common.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Util/Common.cpp.i
.PHONY : Source/Util/Common.cpp.i

Source/Util/Common.s: Source/Util/Common.cpp.s

.PHONY : Source/Util/Common.s

# target to generate assembly for a file
Source/Util/Common.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Util/Common.cpp.s
.PHONY : Source/Util/Common.cpp.s

Source/Util/Random.o: Source/Util/Random.cpp.o

.PHONY : Source/Util/Random.o

# target to build an object file
Source/Util/Random.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Util/Random.cpp.o
.PHONY : Source/Util/Random.cpp.o

Source/Util/Random.i: Source/Util/Random.cpp.i

.PHONY : Source/Util/Random.i

# target to preprocess a source file
Source/Util/Random.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Util/Random.cpp.i
.PHONY : Source/Util/Random.cpp.i

Source/Util/Random.s: Source/Util/Random.cpp.s

.PHONY : Source/Util/Random.s

# target to generate assembly for a file
Source/Util/Random.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/Util/Random.cpp.s
.PHONY : Source/Util/Random.cpp.s

Source/main.o: Source/main.cpp.o

.PHONY : Source/main.o

# target to build an object file
Source/main.cpp.o:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/main.cpp.o
.PHONY : Source/main.cpp.o

Source/main.i: Source/main.cpp.i

.PHONY : Source/main.i

# target to preprocess a source file
Source/main.cpp.i:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/main.cpp.i
.PHONY : Source/main.cpp.i

Source/main.s: Source/main.cpp.s

.PHONY : Source/main.s

# target to generate assembly for a file
Source/main.cpp.s:
	$(MAKE) -f CMakeFiles/empire.dir/build.make CMakeFiles/empire.dir/Source/main.cpp.s
.PHONY : Source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... empire"
	@echo "... edit_cache"
	@echo "... Source/Application.o"
	@echo "... Source/Application.i"
	@echo "... Source/Application.s"
	@echo "... Source/ResourceManager/ResourceHolder.o"
	@echo "... Source/ResourceManager/ResourceHolder.i"
	@echo "... Source/ResourceManager/ResourceHolder.s"
	@echo "... Source/Sim/Colony.o"
	@echo "... Source/Sim/Colony.i"
	@echo "... Source/Sim/Colony.s"
	@echo "... Source/Sim/Person.o"
	@echo "... Source/Sim/Person.i"
	@echo "... Source/Sim/Person.s"
	@echo "... Source/Sim/World.o"
	@echo "... Source/Sim/World.i"
	@echo "... Source/Sim/World.s"
	@echo "... Source/Util/Common.o"
	@echo "... Source/Util/Common.i"
	@echo "... Source/Util/Common.s"
	@echo "... Source/Util/Random.o"
	@echo "... Source/Util/Random.i"
	@echo "... Source/Util/Random.s"
	@echo "... Source/main.o"
	@echo "... Source/main.i"
	@echo "... Source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

